---
# tasks file for node-exporter
- name: Create Node Exporter group
  group:
    name: '{{ node_exporter_user }}'
    system: true
    state: present
  register: group

- name: Create system user
  user:
    name: '{{ node_exporter_user }}'
    create_home: false
    group: '{{ group.name }}'
    system: '{{ group.system }}'
    state: present
  register: user

- name: Extract NodeExporter files
  unarchive:
    src: node_exporter-1.7.0.linux-arm64.tar.gz
    dest: /opt
    owner: '{{ user.name }}'
    group: '{{ group.name }}'
    mode: '0775'
  notify: restart node-exporter

- name: Creating systemd service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart node-exporter
